# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-12-10 22:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='notes',
            field=models.TextField(default='no value', max_length=1000),
            preserve_default=False,
        ),
    ]
