# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-12-10 22:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0002_author_notes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='author',
            new_name='books',
        ),
    ]
