# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-12-11 22:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='description',
            field=models.TextField(default='now value', max_length=1000),
            preserve_default=False,
        ),
    ]
