# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-12-10 21:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ninjas_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojo',
            name='desc',
            field=models.CharField(default='no value', max_length=255),
            preserve_default=False,
        ),
    ]
